### ISSUE TITLE
query_dataset_default_graphs_get uses POST

### ISSUE THREAD

**Issue by gkellogg** [kasei/sparql11-protocolvalidator#1]
The description in the README for query_dataset_default_graphs_get uses the same body as for query_dataset_default_graphs_post. Presumably it should use GET not POST.

**Comment by gkellogg** [comment]
query_dataset_named_graphs_get should probably use GET too.

**Comment by kasei** [comment]
Good catch. I'll fix those shortly.

**Comment by gkellogg** [comment]
I was adding those descriptions into the manifest in the rdf-tests repo (see recent PR). Did much the same for the graph protocols. That may end up being a better home for these descriptions.
